### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by ProtectedMode** [tomaka/glutin#237]
When I try to add glutin as a dependency on Windows, I get a message nearly instantly:
```
Package 'winapi v0.1.3' does not have these features: 'user32, gdi32, kernel32'
```
Hopefully I'm not doing something wrong. Please tell if you need any additional information.

**Comment by tomaka** [comment]
Are you using the version on crates.io?
If so, could you try the github version instead?

```toml
[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
```
